export const RESEND_OTP_WAIT_TIME_IN_SECONDS = 60;
export const DEFAULT_PAGE_SIZE = 20;
export const RESEND_OTP_ON_EDIT_WAIT_TIME_IN_SECONDS = 60;
export const NOTIFICATION_REFRESH_INTERVAL_IN_MINUTES = 30;
